# Generated by Django 5.2.10 on 2026-01-24 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostcodeDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Postcode District',
                'verbose_name_plural': 'Postcode Districts',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AreaScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hmo_score', models.IntegerField(default=0, help_text='Overall HMO investment score (0-100)')),
                ('average_yield', models.DecimalField(blank=True, decimal_places=2, help_text='Average rental yield percentage', max_digits=5, null=True)),
                ('average_price', models.IntegerField(blank=True, help_text='Average property price in GBP', null=True)),
                ('average_rent', models.IntegerField(blank=True, help_text='Average monthly room rent in GBP', null=True)),
                ('demand_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', help_text='Room demand level', max_length=10)),
                ('transport_score', models.IntegerField(default=5, help_text='Transport connectivity score (1-10)')),
                ('has_article_4', models.BooleanField(default=False, help_text='Whether Article 4 Direction applies')),
                ('student_area', models.BooleanField(default=False, help_text='Whether this is a student-heavy area')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('postcode_district', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='areas.postcodedistrict')),
            ],
            options={
                'verbose_name': 'Area Score',
                'verbose_name_plural': 'Area Scores',
            },
        ),
    ]
