# Generated by Django 5.2.10 on 2026-01-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcodedistrict',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='postcodedistrict',
            name='households',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postcodedistrict',
            name='population',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
