# Generated by Django 5.2.10 on 2026-02-14 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_postcodedistrict_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AreaScore',
        ),
    ]
