# Generated by Django 5.2.10 on 2026-02-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0003_delete_areascore'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcodedistrict',
            name='active_postcode_count',
            field=models.IntegerField(blank=True, help_text='Active postcodes in district', null=True),
        ),
        migrations.AddField(
            model_name='postcodedistrict',
            name='easting',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postcodedistrict',
            name='grid_reference',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='postcodedistrict',
            name='nearby_districts',
            field=models.CharField(blank=True, default='', help_text='Comma-separated nearby district codes', max_length=500),
        ),
        migrations.AddField(
            model_name='postcodedistrict',
            name='northing',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postcodedistrict',
            name='post_town',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='postcodedistrict',
            name='postcode_count',
            field=models.IntegerField(blank=True, help_text='Total postcodes in district', null=True),
        ),
        migrations.AddField(
            model_name='postcodedistrict',
            name='uk_region',
            field=models.CharField(blank=True, default='', help_text='UK region (e.g. Scotland, London)', max_length=100),
        ),
        migrations.AlterField(
            model_name='postcodedistrict',
            name='name',
            field=models.CharField(help_text='Town/Area name', max_length=255),
        ),
        migrations.AlterField(
            model_name='postcodedistrict',
            name='region',
            field=models.CharField(help_text='Local region (e.g. Aberdeen, London)', max_length=100),
        ),
    ]
