# Generated by Django 5.2.10 on 2026-02-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0004_postcodedistrict_active_postcode_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcodedistrict',
            name='name',
            field=models.TextField(help_text='Town/Area name'),
        ),
    ]
