# Generated by Django 5.2.10 on 2026-02-14 16:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocalAuthorityDemand',
            fields=[
                ('la_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('la_name', models.CharField(db_index=True, max_length=200)),
                ('region', models.CharField(db_index=True, max_length=100)),
                ('total_population', models.IntegerField()),
                ('population_20_34', models.IntegerField()),
                ('private_renters_20_34', models.IntegerField()),
                ('single_person_households_under66', models.IntegerField()),
                ('young_renter_density', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('young_population_share', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('renting_propensity', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('single_household_density', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('demand_score', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('demand_classification', models.CharField(blank=True, max_length=20, null=True)),
                ('national_rank', models.IntegerField(blank=True, null=True)),
                ('regional_rank', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Local Authority Demand',
                'verbose_name_plural': 'Local Authority Demand Records',
                'ordering': ['la_name'],
            },
        ),
        migrations.CreateModel(
            name='Outcode',
            fields=[
                ('outcode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('local_authority_code', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('local_authority_name', models.CharField(blank=True, max_length=200, null=True)),
                ('region', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
            ],
            options={
                'verbose_name': 'Outcode',
                'verbose_name_plural': 'Outcodes',
                'ordering': ['outcode'],
            },
        ),
        migrations.CreateModel(
            name='RailwayStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(db_index=True, max_length=200)),
                ('tlc_code', models.CharField(help_text='Three-letter CRS code', max_length=3, unique=True)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('annual_entries_exits', models.IntegerField(blank=True, help_text='Passenger usage from ORR data', null=True)),
                ('outcode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stations', to='hmo.outcode')),
            ],
            options={
                'verbose_name': 'Railway Station',
                'verbose_name_plural': 'Railway Stations',
                'ordering': ['station_name'],
            },
        ),
        migrations.CreateModel(
            name='SpareRoomRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(db_index=True, max_length=200)),
                ('avg_room_rent', models.DecimalField(decimal_places=2, help_text='Average monthly room rent in GBP', max_digits=8)),
                ('quarter', models.CharField(help_text='e.g. Q4', max_length=4)),
                ('year', models.IntegerField(help_text='e.g. 2024')),
            ],
            options={
                'verbose_name': 'SpareRoom Rent',
                'verbose_name_plural': 'SpareRoom Rents',
                'ordering': ['-year', 'quarter', 'location_name'],
                'unique_together': {('location_name', 'quarter', 'year')},
            },
        ),
        migrations.CreateModel(
            name='OutcodeLAMapping',
            fields=[
                ('outcode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='la_mapping', serialize=False, to='hmo.outcode')),
                ('local_authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcodes', to='hmo.localauthoritydemand')),
            ],
            options={
                'verbose_name': 'Outcode → LA Mapping',
                'verbose_name_plural': 'Outcode → LA Mappings',
            },
        ),
        migrations.CreateModel(
            name='OutcodeScore',
            fields=[
                ('outcode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='score', serialize=False, to='hmo.outcode')),
                ('transport_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('demand_score', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('yield_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('hmo_score', models.DecimalField(db_index=True, decimal_places=2, default=0, help_text='Composite HMO investment score (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('avg_rent', models.DecimalField(blank=True, decimal_places=2, help_text='Average monthly room rent in GBP', max_digits=8, null=True)),
                ('avg_price', models.DecimalField(blank=True, decimal_places=2, help_text='Average property price in GBP', max_digits=12, null=True)),
                ('avg_yield', models.DecimalField(blank=True, db_index=True, decimal_places=2, help_text='Average yield percentage', max_digits=5, null=True)),
                ('demand_classification', models.CharField(choices=[('Very High', 'Very High'), ('High', 'High'), ('Moderate', 'Moderate'), ('Low', 'Low'), ('Very Low', 'Very Low')], default='Moderate', max_length=20)),
                ('article_4_direction', models.BooleanField(default=False)),
                ('is_student_area', models.BooleanField(default=False)),
                ('nearest_station_name', models.CharField(blank=True, max_length=200, null=True)),
                ('nearest_station_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('london_journey_mins', models.IntegerField(blank=True, null=True)),
                ('nearest_city_journey_mins', models.IntegerField(blank=True, null=True)),
                ('nearest_city_name', models.CharField(blank=True, max_length=200, null=True)),
                ('cities_within_60_mins', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Outcode Score',
                'verbose_name_plural': 'Outcode Scores',
                'indexes': [models.Index(fields=['-hmo_score'], name='idx_outcodescore_hmo'), models.Index(fields=['-demand_score'], name='idx_outcodescore_demand'), models.Index(fields=['transport_score'], name='idx_outcodescore_transport'), models.Index(fields=['-avg_yield'], name='idx_outcodescore_yield')],
            },
        ),
        migrations.CreateModel(
            name='StationCityJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=200)),
                ('journey_time_mins', models.IntegerField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_journeys', to='hmo.railwaystation')),
            ],
            options={
                'verbose_name': 'Station City Journey',
                'verbose_name_plural': 'Station City Journeys',
                'ordering': ['station', 'journey_time_mins'],
                'unique_together': {('station', 'city_name')},
            },
        ),
    ]
