# Generated by Django 5.2.10 on 2026-02-14 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmo', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stationcityjourney',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='stationcityjourney',
            name='station',
        ),
        migrations.DeleteModel(
            name='StationCityJourney',
        ),
        migrations.DeleteModel(
            name='RailwayStation',
        ),
    ]
