# Generated by Django 5.2.10 on 2026-02-14 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0003_delete_areascore'),
        ('hmo', '0003_alter_outcodelamapping_outcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HmoScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hmo_score', models.IntegerField(default=0, help_text='Overall HMO investment score (0-100)')),
                ('average_yield', models.DecimalField(blank=True, decimal_places=2, help_text='Average rental yield percentage', max_digits=5, null=True)),
                ('average_price', models.IntegerField(blank=True, help_text='Average property price in GBP', null=True)),
                ('average_rent', models.IntegerField(blank=True, help_text='Average monthly room rent in GBP', null=True)),
                ('demand_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', help_text='Room demand level', max_length=10)),
                ('transport_score', models.IntegerField(default=5, help_text='Transport connectivity score (1-10)')),
                ('council_attitude_score', models.IntegerField(default=5, help_text='Council attitude towards HMOs (1-10)')),
                ('has_article_4', models.BooleanField(default=False, help_text='Whether Article 4 Direction applies')),
                ('student_area', models.BooleanField(default=False, help_text='Whether this is a student-heavy area')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('postcode_district', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='areas.postcodedistrict')),
            ],
            options={
                'verbose_name': 'HMO Score',
                'verbose_name_plural': 'HMO Scores',
            },
        ),
        migrations.DeleteModel(
            name='AreaScore',
        ),
    ]
