# Generated by Django 5.2.10 on 2026-02-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmo', '0004_hmoscore_delete_areascore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hmoscore',
            name='demand_level',
        ),
        migrations.AddField(
            model_name='hmoscore',
            name='demand_score',
            field=models.IntegerField(default=50, help_text='Room demand score (0-100)'),
        ),
    ]
