# Generated by Django 5.2.10 on 2026-02-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmo', '0005_remove_hmoscore_demand_level_hmoscore_demand_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localauthoritydemand',
            name='la_code',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='localauthoritydemand',
            name='population_20_34',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='localauthoritydemand',
            name='private_renters_20_34',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='localauthoritydemand',
            name='single_person_households_under66',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='localauthoritydemand',
            name='total_population',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
