# Generated by Django 5.2.10 on 2026-02-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmo', '0006_alter_localauthoritydemand_la_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hmoscore',
            name='cities_within_60_mins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hmoscore',
            name='london_journey_mins',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hmoscore',
            name='nearest_city_journey_mins',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hmoscore',
            name='nearest_city_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hmoscore',
            name='nearest_station_distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='hmoscore',
            name='nearest_station_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hmoscore',
            name='transport_score',
            field=models.IntegerField(default=0, help_text='Transport connectivity score (0-100)'),
        ),
    ]
