# Generated by Django 5.2.10 on 2026-02-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutcodePropertyStats',
            fields=[
                ('outcode', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('avg_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('median_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('avg_price_per_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_count', models.IntegerField()),
                ('avg_floor_area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('data_from_date', models.DateField()),
                ('data_to_date', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Outcode Property Stats',
                'verbose_name_plural': 'Outcode Property Stats',
                'ordering': ['outcode'],
            },
        ),
        migrations.CreateModel(
            name='OutcodePropertyStatsByType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcode', models.CharField(db_index=True, max_length=4)),
                ('property_type', models.CharField(choices=[('D', 'Detached'), ('S', 'Semi-Detached'), ('T', 'Terraced'), ('F', 'Flat'), ('O', 'Other')], db_index=True, max_length=1)),
                ('avg_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('median_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('avg_price_per_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('transaction_count', models.IntegerField()),
                ('avg_floor_area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Outcode Property Stats by Type',
                'verbose_name_plural': 'Outcode Property Stats by Type',
                'ordering': ['outcode', 'property_type'],
                'unique_together': {('outcode', 'property_type')},
            },
        ),
        migrations.CreateModel(
            name='PropertyTransaction',
            fields=[
                ('transaction_id', models.CharField(max_length=38, primary_key=True, serialize=False)),
                ('price', models.PositiveIntegerField()),
                ('date_of_transfer', models.DateField(db_index=True)),
                ('postcode', models.CharField(db_index=True, max_length=8)),
                ('outcode', models.CharField(db_index=True, max_length=4)),
                ('property_type', models.CharField(choices=[('D', 'Detached'), ('S', 'Semi-Detached'), ('T', 'Terraced'), ('F', 'Flat'), ('O', 'Other')], db_index=True, max_length=1)),
                ('old_new', models.CharField(choices=[('Y', 'New Build'), ('N', 'Established')], max_length=1)),
                ('duration', models.CharField(choices=[('F', 'Freehold'), ('L', 'Leasehold')], max_length=1)),
                ('paon', models.CharField(blank=True, max_length=100)),
                ('saon', models.CharField(blank=True, max_length=100)),
                ('street', models.CharField(blank=True, max_length=200)),
                ('locality', models.CharField(blank=True, max_length=200)),
                ('town_city', models.CharField(blank=True, max_length=200)),
                ('district', models.CharField(blank=True, max_length=200)),
                ('county', models.CharField(blank=True, max_length=200)),
                ('ppd_category', models.CharField(choices=[('A', 'Standard Price Paid'), ('B', 'Additional Price Paid')], max_length=1)),
                ('record_status', models.CharField(choices=[('A', 'Addition'), ('C', 'Change'), ('D', 'Delete')], max_length=1)),
                ('total_floor_area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('price_per_sqm', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated: price / total_floor_area_sqm', max_digits=10, null=True)),
                ('property_type_epc', models.CharField(blank=True, help_text='Detailed EPC type e.g. "End-Terrace", "Ground-Floor Flat"', max_length=50, null=True)),
                ('number_habitable_rooms', models.IntegerField(blank=True, null=True)),
                ('construction_age_band', models.CharField(blank=True, help_text='e.g. "1976-1982"', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Property Transaction',
                'verbose_name_plural': 'Property Transactions',
                'ordering': ['-date_of_transfer'],
                'indexes': [models.Index(fields=['outcode', 'date_of_transfer'], name='idx_proptx_outcode_date'), models.Index(fields=['outcode', 'property_type'], name='idx_proptx_outcode_type')],
            },
        ),
    ]
