# Generated by Django 5.2.10 on 2026-02-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EPCImportProgress',
            fields=[
                ('outcode', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('error', 'Error')], default='pending', max_length=20)),
                ('records_fetched', models.IntegerField(default=0)),
                ('records_matched', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'EPC Import Progress',
                'verbose_name_plural': 'EPC Import Progress',
                'ordering': ['outcode'],
            },
        ),
    ]
