# Generated by Django 5.2.10 on 2026-02-14 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hmo', '0002_remove_stationcityjourney_station_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MajorCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('station_codes', models.JSONField()),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('population', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Major Cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RailwayStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(db_index=True, max_length=200)),
                ('tlc_code', models.CharField(max_length=3, unique=True)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('annual_entries_exits', models.IntegerField(blank=True, null=True)),
                ('outcode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stations', to='hmo.outcode')),
            ],
            options={
                'ordering': ['station_name'],
            },
        ),
        migrations.CreateModel(
            name='StationCityJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('journey_time_mins', models.IntegerField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to='transport.railwaystation')),
            ],
            options={
                'unique_together': {('station', 'city_name')},
            },
        ),
    ]
