# Generated by Django 5.2.10 on 2026-02-14 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0003_delete_areascore'),
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='railwaystation',
            name='outcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stations', to='areas.postcodedistrict', to_field='code'),
        ),
    ]
