# Generated by Django 5.2.10 on 2026-02-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_alter_railwaystation_outcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationcityjourney',
            name='journey_time_mins',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
