# Generated by Django 5.2.10 on 2026-02-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_alter_stationcityjourney_journey_time_mins'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationcityjourney',
            name='destination_station',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
